public class q4_1_a {
    public static void main(String[] args) {
        System.out.println("________________________________");
        System.out.println(Math.sqrt(4));
        System.out.println(Math.sin(2*Math.PI));
        System.out.println(Math.cos(2*Math.PI));
        System.out.println(Math.pow(2,2));
        System.out.println(Math.log(Math.E));
        System.out.println(Math.max(2,Math.min(3,4)));
        System.out.println(Math.exp(1));
        System.out.println(Math.rint(-2.5));
        System.out.println(Math.ceil(-2.5));
        System.out.println(Math.floor(-2.5));
        System.out.println(Math.round(-2.5f));
        System.out.println(Math.round(-2.5));
        System.out.println(Math.rint(2.5));
        System.out.println(Math.ceil(2.5));
        System.out.println(Math.floor(2.5));
        System.out.println(Math.round(2.5f));
        System.out.println(Math.round(2.5));
        System.out.println(Math.round(Math.abs(-2.5)));
       System.out.println("_____________________________________");
       double degreeToRadians = Math.toRadians(47);
       System.out.println(degreeToRadians);
       System.out.println("_____________________________________");
       int random= (int)(Math.random()*1000);
       System.out.println(random);

       System.out.println("_____________________");
    System.out.println(Math.log(Math.exp(5.5)));
    System.out.println(Math.exp(Math.log(5.5)));
    System.out.println(Math.sin(Math.PI/6));
    System.out.println(Math.sin(Math.asin(Math.PI/6)));
     int range = 34+(int)(Math.random()*(55-34+1));
     System.out.println(range);
     double range1 = 5.5 + Math.random()*(55.5-5.5+1);
     System.out.println(range1);
     System.out.println("----\t---\t----\t");
    char c = '1';
     System.out.println((int)(c));
     char a = 'A';
     System.out.println((int)(a));
     char b = 'B';
     System.out.println((int)(b));
     
     char d = 'a';
     System.out.println((int)(d));
     
     char e = 'b';
     System.out.println((int)(e));
     
     int f =40;
     System.out.println((char)f);
     int g = 59;
     System.out.println((char)g);
     int h = 79;
     System.out.println((char)h);
     System.out.println((char)85);
     System.out.println((char)90);
     System.out.println((char)40);
     System.out.println((char)(0X5A));
     System.out.println((char)(0x71));
     System.out.println((char)0x72);
     System.out.println((char)0x7A);
     System.out.println('I');
   // char u ='\u345dE';
     //System.out.println((char)u);
     char hh ='\u3fFa';
     System.out.println(hh);
     char bd='\b';
     System.out.println(bd);
     char sf='\t';
     System.out.println(sf);
     int ii='l';
     System.out.println(ii);
     int jj = 'l'+'2'*('4' - '3')+'b' / 'a' ;
     System.out.println(jj);
     int kk = 'a';
     System.out.println(kk);
    char cs = 90;
     System.out.println(cs);
     char ccc ='A';
     int i =(int)ccc;
          System.out.println(i);
          float ff=1000.34f;
           int af =(int)ff;
           System.out.println(af);
           double dd = 1000.34;
           int isf = (int)dd;
           System.out.println(isf);
           int ifg = 97;
           char j = (char)ifg;
           System.out.println(j);
           char x ='a';
           char y ='b';
           System.out.println(++x);
           System.out.println(y++);
           System.out.println(x -y);
           
        int random_lower_case=97+(int)(Math.random()* (122 - 97+1));
           System.out.println((char)random_lower_case);
           System.out.println('a' < 'b');
System.out.println('a' <= 'A');
System.out.println('a' > 'b');
System.out.println('a' >= 'A');
System.out.println('a' == 'a');
System.out.println('a' != 'b');
System.out.println("isDigit('a') is"+Character.isDigit('a'));
System.out.println(Character.isDigit('3'));
char afds='c';
System.out.println(Character.isLetter(afds));
System.out.println(Character.isLetterOrDigit(afds));
System.out.println(Character.isLowerCase(afds));
System.out.println(Character.isUpperCase(afds));
System.out.println(Character.toLowerCase(afds));
System.out.println(Character.toUpperCase(afds));
String message = " ";

System.out.println("The length of "+message+"is"+message.length());
 System.out.println("---------------------------------------");
String name="Anupriya Rani";
System.out.println("Length of name is"+name.length());
System.out.println(name.charAt(0));
System.out.println(name.charAt(1));
System.out.println(name.charAt(2));
System.out.println(name.charAt(3));
System.out.println(name.charAt(4));
System.out.println(name.charAt(5));
System.out.println(name.charAt(6));
System.out.println(name.charAt(7));
System.out.println(name.charAt(8));
System.out.println(name.charAt(9));
System.out.println(name.charAt(10));
System.out.println(name.charAt(11));
System.out.println(name.charAt(12));
//System.out.println(name.charAt(13));
//System.out.println(name.charAt(14));
String s="1234a";
System.out.println(name.concat(s));
System.out.println(s.toUpperCase());
System.out.println(name.toUpperCase());
System.out.println(s.toLowerCase());
System.out.println(s.toUpperCase());
System.out.println("--------------------------------");
String ee="Anupriya";
System.out.println(ee.equals("Anupriya"));
System.out.println(ee.equals("anupriya"));
System.out.println(ee.equalsIgnoreCase("anupriya"));
 System.out.println(ee.equalsIgnoreCase("Anupriya"));      
System.out.println(ee.compareTo("Anupriya"));
 System.out.println(ee.compareTo("anupriya"));
 System.out.println(ee.compareTo("cat"));
System.out.println(ee.compareTo("Anupriya Rani"));
System.out.println(ee.compareTo("a"));
System.out.println(ee.compareToIgnoreCase("anupriya"));
System.out.println(ee.compareToIgnoreCase("aa"));
System.out.println(ee.compareToIgnoreCase("z"));
System.out.println(ee.startsWith("priya"));
System.out.println(ee.startsWith("a"));
System.out.println(ee.startsWith("A"));
System.out.println(ee.contains("riya"));
System.out.println(ee.contains("anuy"));
System.out.println(ee.contains("ANupriya"));
System.out.println(ee.endsWith("nu"));
System.out.println(ee.endsWith("a"));
System.out.println(ee.endsWith("ya"));
System.out.println(ee.endsWith("priya"));
System.out.println(ee.endsWith("Anupriya"));
 System.out.println("_________________")
 ;
 String  sa ="Welcome to Java";
 System.out.println(sa.substring(11));   
 String st = "Geeky shows";
 System.out.println(st.substring(5));
 System.out.println(st.substring(3 ,8 ));
System.out.println(sa.trim());
System.out.println(sa.length());
System.out.println(sa.charAt(0));
System.out.println(sa.concat(" Anupriya"));
System.out.println(sa.indexOf('a'));
System.out.println(sa.indexOf('0'));
System.out.println(sa.indexOf('W'));
System.out.println(sa.indexOf('e'));
System.out.println(sa.lastIndexOf('e'));
String str = "111";
int t=Integer.parseInt(str);
System.out.println(t);
String sss ="135324";
int kkh = Integer.parseInt(sss);
System.out.println(kkh);
System.out.println("-----------------------------------");
  String s1 ="Welcome to java";
  String s2 ="Programmimg is fun";
  String s3 ="Welcome to java";
  System.out.println(s1==s2);
  System.out.println(s2==s3);
  System.out.println(s1.equals(s2));
  System.out.println(s1.equals(s3));
  System.out.println(s1.compareTo(s2));
  System.out.println(s2.compareTo(s3));
  System.out.println(s2.compareTo(s2));
  System.out.println(s1.charAt(0));
  System.out.println(s1.indexOf('j'));
  System.out.println(s1.indexOf("o"));
  System.out.println(s1.lastIndexOf('a'));
  System.out.println(s1.lastIndexOf("o",15));
  System.out.println(s1.length());
  System.out.println(s1.substring(5));
  System.out.println(s1.startsWith("Wel"));
  System.out.println(s1.endsWith("java"));
  System.out.println(s1.toLowerCase());
  System.out.println(s1.toUpperCase());
  System.out.println(s1.concat(s2));
  System.out.println(s1.contains(s2));
  System.out.println("\t Wel \t".trim());
  
}
}